Feature/jira oauth
KanSync/kansync-server pull request #39
Opened 2023-12-07 15:29 UTC by Dan-cmyk

Closes: #34

2023-12-07 15:37 UTC, richyk1 requested changes

2023-12-07 15:37 UTC, richyk1 commented on functions/jira/auth/token.ts
> +const BACKEND_URL = "https://local.functions.nhost.run/v1/jira/auth/token";
These URLs are most likely going to change once the website gets deployed to Netlify, how do you plan on solving that change?

2023-12-07 15:37 UTC, richyk1 commented on functions/jira/callAPI.ts
> +  // @ts-ignore
We want to avoid ignoring Typescript rules, was there no other way to solve this without disabling them?

2023-12-07 15:37 UTC, richyk1 commented on functions/jira/callAPI.ts
> +  // @ts-ignore
Same here

2023-12-11 12:26 UTC, richyk1 approved these changes
Looks good!

2023-12-11 12:34 UTC, amermsl92 approved these changes

2023-12-11 13:12 UTC, merged